name: "run-tests"

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        php: [7.2, 7.3, 7.4]
        laravel: [5.7.*, 6.*, 7.*]
        include:
            - laravel: 7.*
              testbench: 5.*
            - laravel: 6.*
              testbench: 4.*
            - laravel: 5.7.*
              testbench: 3.7.*

    name: PHP ${{ matrix.php }} / L ${{ matrix.laravel }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: ~/.composer/cache/files
          key: dependencies-laravel-${{ matrix.laravel }}-php-${{ matrix.php }}-composer-${{ hashFiles('composer.json') }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: xdebug

      - name: Install dependencies
        run: |
          composer require "laravel/framework:${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.testbench }}" --no-interaction --no-update
          composer update --prefer-dist --no-interaction --no-suggest

      - name: Execute tests
        run: vendor/bin/phpunit --coverage-clover clover.xml

      - name: Store coverage report
        uses: actions/upload-artifact@v2
        with:
          name: coverage-report
          path: clover.xml

  coverage:
    runs-on: ubuntu-latest

    needs: [test]

    name: Code coverage

    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
          coverage: none

      - name: Download coverage report
        uses: actions/download-artifact@v2
        with:
          name: coverage-report

      - name: Submit code coverage report
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          composer global require cedx/coveralls
          coveralls clover.xml
